---
version: 0.2.2
hassio_api: true
slug: uacme
name: UACME Home Assistant ACME client
description: A ACME client
url: https://github.com/Cronvs/hassio-uacme-addon
arch:
  - aarch64
  - amd64
init: false
image: ghcr.io/cronvs/hassio-uacme-addon
map:
  - type: ssl
    read_only: false
options:
  domain: null
  hook: /ssl/zns.sh
  refresh: "-s 1d"
schema:
  domain: str
  acmedir: str?
  hook: str
  eab: str?
  refresh: str
