name: Build and Publish Add-on

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build multi-arch addon
        uses: home-assistant/builder@master
        with:
          args: --amd64 --aarch64 --target . --image ghcr.io/${{ github.repository }} --docker-hub ${{ secrets.GITHUB_TOKEN }}
